#!/bin/bash
set -e

cd /workspaces/competitive/library
oj-verify --config-file /workspaces/competitive/.bin/verifyconfig run
oj-verify docs
cd .verify-helper/markdown
git add .
git commit -m "update markdown files"
git push
