#!/bin/bash
set -e

cd /workspaces/competitive/library
oj-verify --config-file /workspaces/competitive/.bin/verifyconfig run
oj-verify docs
# マークダウンを docs にコピーしてコミット & プッシュ
cp -r library/.verify-helper/markdown/* docs/
git add docs
git commit -m "Update markdown docs for GitHub Pages"
git push
